NamespaceMapper: conform to cloud pluralized stacks-<id> namespace
grafana/authlib pull request #73
Opened 2024-08-22 19:37 UTC by charandas

There has been some miscommunication within our working group and it made its way into OSS code and into auth/authlib, which is that cloud namespace format is `stack-<stackID>`.

This is incorrect. Cloud namespaces are `stacks-<stackId>` historically.

[Slack convo](https://raintank-corp.slack.com/archives/C037H5GAY9L/p1724257160817399?thread_ts=1722433605.876979&cid=C037H5GAY9L).

2024-08-22 21:43 UTC, toddtreece commented on authz/namespace.go
> +	DefaultStackIDMetadataKey = "X-stacks-ID"
does this need to change?

2024-08-23 06:25 UTC, kalleep requested changes
Okey, this requires a bit more work. We need to update in at least one other place before we merge this one so lets hold this one until that work is done

2024-08-23 06:25 UTC, kalleep commented on authz/namespace.go
> +	DefaultStackIDMetadataKey = "X-stacks-ID"
Probably result of search and replace

2024-08-23 22:51 UTC, charandas commented on authz/namespace.go
> +	DefaultStackIDMetadataKey = "X-stacks-ID"
Will revert

2024-08-23 22:54 UTC, charandas commented on authz/namespace.go
>  type NamespaceAccessChecker interface {
I am thinking of using this interface in both `ext_jwt` in OSS and in other places in enterprise. But its original contract is not gonna help with resolving the ambiguity, so I moved that to `CheckAccessForIdentitifer` (`Identifier` instead of `StackID` to be more general).

2024-08-24 00:23 UTC, charandas commented on authz/namespace.go
>  type NamespaceAccessChecker interface {
Here are the associated OSS changes: https://github.com/grafana/grafana/pull/92332/commits/b5807e210a0efecc522170a43b5bb86679bccca6

2024-08-24 00:32 UTC, charandas commented
[L90](https://github.com/grafana/authlib/blob/main/authz/namespace.go#L90C13-L90C54) in current main won't work, as service layer when acting on behalf of the user may call `namespaceAccessChecker.Check(requester, "*")` but since id tokens never have such a claim, L90 would fail the check, when it should actually let it pass. So I will add some check for that.

2024-08-24 01:07 UTC, charandas commented on authz/namespace.go
> +	if checkerType == NamespaceAccessCheckerTypeCloud && (actualNamespaceParts[0] == "stack" || actualNamespaceParts[0] == "stacks") && expectedNamespaceParts[0] == "stacks" {
Since `expectedNamespace` is generated by the library, it doesn't need the singular case. Maybe not very intuitive, but efficient!

2024-08-26 06:42 UTC, gamab commented on claims/namespace.go
> +		stackId, err := strconv.Atoi(stackIDStr)
Why this change?

2024-08-26 06:44 UTC, gamab commented on claims/namespace.go
>  		stackIDStr := ns[6:]
```suggestion
	if strings.HasPrefix(ns, "stacks-") {
		stackIDStr := ns[7:]
```

2024-08-26 06:56 UTC, kalleep commented on claims/namespace.go
> +	if strings.HasPrefix(ns, "stacks-") {
Maybe we should handle both formats here for now? At least as long as we support writing them

2024-08-26 06:56 UTC, kalleep commented on claims/namespace.go
>  		stackIDStr := ns[6:]
Probably easier to just use [strings.CutPrefix](https://pkg.go.dev/strings#CutPrefix).
```go
if id, ok := strings.CutPrefix(ns, "stacks-1"); ok {
  stackId, err := strconv.Atoi(id)
  // ....
}
```

2024-08-26 15:19 UTC, charandas commented on claims/namespace.go
> +		stackId, err := strconv.Atoi(stackIDStr)
Unintentional. Will revert. The block probably came from another repo where I was doing a similar check.

2024-08-27 08:29 UTC, gamab commented on authz/namespace.go
> +	CheckAccessForIdentitfier(caller claims.AuthInfo, id int64) error
Personal preference:
```go
	CheckAccessForId(caller claims.AuthInfo, id int64) error
```
or
```go
	CheckAccessById(caller claims.AuthInfo, id int64) error
```

2024-08-27 08:50 UTC, gamab commented on authz/namespace.go
> +		} else if expectedNamespace != "*" && !checkEqualsNamespaceDisambiguous(expectedNamespace, idClaims.Namespace(), na.checkerType) {
If there is an id token, then AuthInfo represents a user. If `expectedNamespace == "*"` we should hence fail as I don't think a user can access all namespaces.

2024-08-27 09:21 UTC, gamab commented on authz/namespace.go
> +func (na *NamespaceAccessCheckerImpl) CheckAccess(caller claims.AuthInfo, expectedNamespace string) error {
I think we can do something simpler to disambiguate the namespace:
```go
// disambiguousNamespace is a helper to temporarily navigate the issue with cloud namespace claims being ambiguous (stack vs stacks).
func disambiguousNamespace(namespace string) string {
	return strings.Replace(namespace, "stack-", "stacks-", 1)
}

func (na *NamespaceAccessCheckerImpl) CheckAccess(caller claims.AuthInfo, expectedNamespace string) error {
	expectedNamespace = strings.Replace(expectedNamespace, "stack-", "stacks-", 1)
	if na.idTokenEnabled {
		idClaims := caller.GetIdentity()
		if idClaims == nil || idClaims.IsNil() {
			if na.idTokenRequired {
				return ErrorMissingIDToken
			} else {
				namespace := disambiguousNamespace(idClaims.Namespace())
				if namespace != expectedNamespace {
					return ErrorIDTokenNamespaceMismatch
				}
			}
		}
	}
	if na.accessTokenEnabled {
		accessClaims := caller.GetAccess()
		if accessClaims == nil || accessClaims.IsNil() {
			return ErrorMissingAccessToken
		}
		namespace := disambiguousNamespace(accessClaims.Namespace())
		if namespace != "*" && namespace != expectedNamespace {
			return ErrorAccessTokenNamespaceMismatch
		}
	}
	return nil
}
```

2024-08-27 16:26 UTC, charandas commented on authz/namespace.go
> +func (na *NamespaceAccessCheckerImpl) CheckAccess(caller claims.AuthInfo, expectedNamespace string) error {
I like it @gamab. Thanks for sharing, will adapt to using your snippet.

2024-08-27 16:53 UTC, gamab commented on authz/namespace.go
> +		} else if expectedNamespace != "*" && !checkEqualsNamespaceDisambiguous(expectedNamespace, idClaims.Namespace(), na.checkerType) {
@kalleep to confirm. But this does sound weird to me that we'd act on behalf of a user in the global namespace.

2024-08-27 17:37 UTC, kalleep approved these changes

2024-08-27 17:38 UTC, merged